name=Explore1553
version=1.0.0
author=jmussman
maintainer=jmussman
sentence=A modified version of the Flex1553 (https://github.com/bsundahl1/Flex1553) library supporting the Explore1553 sandbox.
paragraph=This library enables high-speed 1553 protocol handling by leveraging the specialized FlexIO hardware on the IMXRT1060 processor.
category=Communication
url=https://github.com/bsundahl1/Explore1553
architectures=teensy4
includes=Flex1553.h